# Generated by Django 3.2.18 on 2023-02-25 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eatdapoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergametype',
            name='game_type',
            field=models.CharField(choices=[('MealPlan', 'MealPlan'), ('CalorieCounting', 'CalorieCounting')], default='MealPlan', max_length=25),
        ),
        migrations.CreateModel(
            name='UserMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.ManyToManyField(to='eatdapoints.Meal')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCalorieCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eatdapoints.calories')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
